name       : kmymoney
version    : 5.0.8
release    : 14
source     :
    - https://cdn.download.kde.org/stable/kmymoney/5.0.8/src/kmymoney-5.0.8.tar.xz : ac6bcef37def09ca2530276254eab5e9ae57f3a1cd5ed7c87c3d38045400d4c0
license    : GPL-2.0-or-later
component  : office.finance
libsplit   : no
summary    : The best Personal Finance Manager
description: |
    The best Personal Finance Manager for FREE Users, full stop.
builddeps  :
    - pkgconfig(aqbanking)
    - pkgconfig(gwengui-qt5)
    - pkgconfig(libalkimia5)
    - pkgconfig(libical)
    - pkgconfig(libKActivities)
    - pkgconfig(libofx)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - akonadi-devel
    - extra-cmake-modules
    - gpgme-devel
    - karchive-devel
    - kcmutils-devel
    - kcontacts-devel
    - kdewebkit-devel
    - kdiagram-devel
    - kdoctools-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - knotifications-devel
    - kpimtextedit-devel
    - kross-devel
    - kwallet-devel
    - libassuan-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
