name       : kmymoney
version    : 5.1.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/kmymoney/5.1.0/src/kmymoney-5.1.0.tar.xz : 2db968f1d112b913fde3e0e5160215ca689ea2ca5ce3f6f00a4ef97330f71351
license    : GPL-2.0-or-later
component  : office.finance
libsplit   : no
summary    : The best Personal Finance Manager
description: |
    The best Personal Finance Manager for FREE Users, full stop.
builddeps  :
    - pkgconfig(aqbanking)
    - pkgconfig(gpgme)
    - pkgconfig(gwengui-qt5)
    - pkgconfig(libalkimia5)
    - pkgconfig(libassuan)
    - pkgconfig(libical)
    - pkgconfig(libKActivities)
    - pkgconfig(libofx)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - akonadi-devel
    - extra-cmake-modules
    - karchive-devel
    - kcmutils-devel
    - kcontacts-devel
    - kdewebkit-devel
    - kdiagram-devel
    - kdoctools-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - knotifications-devel
    - kpimtextedit-devel
    - kross-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # Remove HTML docs
    rm -r $installdir/usr/share/doc
