name       : kmymoney
version    : 5.0.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/kmymoney/5.0.0/src/kmymoney-5.0.0.tar.xz : 984f5866aa7d7bf53d2ef9bbfbb6e5de0d69972f225031ebfd86b46df131f5ba
license    : GPL-2.0
component  : office.finance
libsplit   : no
summary    : The best Personal Finance Manager
description: |
    The best Personal Finance Manager for FREE Users, full stop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libalkimia5)
    - pkgconfig(libical)
    - pkgconfig(libKActivities)
    - pkgconfig(libofx)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - gpgme-devel
    - karchive-devel
    - kcmutils-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kdewebkit-devel
    - kdiagram-devel
    - kdoctools-devel
    - kholidays-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemmodels-devel
    - kitemviews-devel
    - knotifications-devel
    - kross-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwallet-devel
    - kxmlgui-devel
    - libassuan-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
