name       : kmymoney
version    : 5.0.1
release    : 4
source     :
    - https://cdn.download.kde.org/stable/kmymoney/5.0.1/src/kmymoney-5.0.1.tar.xz : dd6e8fc22a48ddcb322565c8f385d6aa44d582cfcf6fe2ff3dc11fc0b6bd2ab1
license    : GPL-2.0
component  : office.finance
libsplit   : no
summary    : The best Personal Finance Manager
description: |
    The best Personal Finance Manager for FREE Users, full stop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libalkimia5)
    - pkgconfig(libical)
    - pkgconfig(libKActivities)
    - pkgconfig(libofx)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - gpgme-devel
    - karchive-devel
    - kcmutils-devel
    - kdewebkit-devel
    - kdiagram-devel
    - kdoctools-devel
    - kholidays-devel
    - kitemmodels-devel
    - knotifications-devel
    - kross-devel
    - kwallet-devel
    - libassuan-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
