name       : kmymoney
version    : 5.0.2
release    : 8
source     :
    - https://origin.download.kde.org/stable/kmymoney/5.0.2/src/kmymoney-5.0.2.tar.xz : 57f321ebdb1e8bc04e41531a7d0ce947c65101d7768c2aa45c65370b5d67a593
license    : GPL-2.0-or-later
component  : office.finance
libsplit   : no
summary    : The best Personal Finance Manager
description: |
    The best Personal Finance Manager for FREE Users, full stop.
builddeps  :
    - pkgconfig(aqbanking)
    - pkgconfig(gl)
    - pkgconfig(gwengui-qt5)
    - pkgconfig(libalkimia5)
    - pkgconfig(libical)
    - pkgconfig(libKActivities)
    - pkgconfig(libofx)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - gpgme-devel
    - karchive-devel
    - kcmutils-devel
    - kdewebkit-devel
    - kdiagram-devel
    - kdoctools-devel
    - kholidays-devel
    - kitemmodels-devel
    - knotifications-devel
    - kross-devel
    - kwallet-devel
    - libassuan-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
