name       : kmymoney
version    : 5.0.7
release    : 12
source     :
    - https://cdn.download.kde.org/stable/kmymoney/5.0.7/src/kmymoney-5.0.7.tar.xz : d5dcac31db410861fe74955109715012bcddfd095cdbb18c91827a77dffeb5c0
license    : GPL-2.0-or-later
component  : office.finance
libsplit   : no
summary    : The best Personal Finance Manager
description: |
    The best Personal Finance Manager for FREE Users, full stop.
builddeps  :
    - pkgconfig(aqbanking)
    - pkgconfig(gwengui-qt5)
    - pkgconfig(libalkimia5)
    - pkgconfig(libical)
    - pkgconfig(libKActivities)
    - pkgconfig(libofx)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - akonadi-devel
    - extra-cmake-modules
    - gpgme-devel
    - karchive-devel
    - kcmutils-devel
    - kcontacts-devel
    - kdewebkit-devel
    - kdiagram-devel
    - kdoctools-devel
    - kholidays-devel
    - kidentitymanagement-devel
    - kitemmodels-devel
    - knotifications-devel
    - kpimtextedit-devel
    - kross-devel
    - kwallet-devel
    - libassuan-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
